### ISSUE TITLE
example mass assigning single keys

### ISSUE THREAD

**Issue by Zer0xFF** [cobacdavid/dtv2#6]
https://github.com/cobacdavid/dtv2/blob/0cf92855c673c664b6137210fe0fa7350ea2455e/examples/dtv2reader/dtv2reader#L26-L28
https://github.com/cobacdavid/dtv2/blob/0cf92855c673c664b6137210fe0fa7350ea2455e/dtv2/dtv2.py#L311-L321

this way of mass assigning individual keys is really expensive, since you open and close the device multiple time.

I think an ideal way would be to pass list of keys, and colours, and loop over them and all while opening/closing once, something like
```python
    def keySets(self, key_colors):
        """ demande l'application d'un changement sur une touche
        """
        self.__ouverture_device()
        for key, colour in key_colors:
            self.__trame_couleur_touche(key, colour)
            self.__ecriture_device()
            # if self.__ecriture_device() == -1:
            #     self.dev.close()
            #     raise Exception('erreur...')
        self.dev.close()
```
note, im ignoring fail writes here (as think it can happen on incorrect key code?).
ofc, `key_colors` can be either a list or dict, and the code can be changed accordingly

example of list https://github.com/Zer0xFF/dtv2/blob/working/event_handler.py#L43 (this is just a quick script i put together to auto change the layout based on focused app)

**Comment by cobacdavid** [comment]
OK excellent suggestion! 

I did like this:
```python
def key_set(self, id_keys, RGB_colors):
        """Multi-keys assignments

        """

        trames = []
        for keys, colors in zip(split_list(id_keys), split_list(RGB_colors)):
            self.__trame_couleur_plusieurs_touches(keys, colors)
            trames.append(self.trame[:])

        self.__applique_trames(trames)
```
It seems to work. I wait before pushing for example script to be re-written and the doc to be updated.
 
I had the same idea of changing colors according to focused window client :) but with `awesome-wm` (actually this is quite simple to manage this event), I did this also with the mouse. As changing colors was too slow (before you gave some help), I just changed whole keyboard color.

**Comment by Zer0xFF** [comment]
ah, though thats linux specific (and my solution is windows specific), so it would be nice having a portable, (perhaps, python based solution), anyway...

that works, but why do you prefer to have keys and colors seperated like this?

**Comment by cobacdavid** [comment]
I guess you're right. It could be better to handle multi-type args.

May be we could transform this `key_set` function name into a (pseudo)-private one `__key_set` and create a `key_set` dealing arg types and pointing to private version?

**Comment by Zer0xFF** [comment]
I've been thinking hard about this XD, i think this is fine, because if you're using `COLOR_NAME_TO_RGB` you will have to pre-process the values anyway, so you'd break them down anyway.

e.g
```python
dico_config = json.loads(config)
keys = dico_config.keys()
values = [colour.COLOR_NAME_TO_RGB[v] for v in dico_config.values()]
kbd.key(keys, values) 
```

personally the only change i would be to make sure len(keys) == len(colors) and change the for loop from `for keys, colors in zip(split_list(id_keys), split_list(RGB_colors)):`, to 
```python
for i in range(len(id_keys)):
  self.__trame_couleur_plusieurs_touches(id_keys[i], RGB_colors[i])
[...]
```
its personal preference and i think it reads better

**Comment by cobacdavid** [comment]
I am also thinking hard about this, now.
Split_list allows packets size to be correct... 5 keys max in a packet.

But I think a big part of code should be rewritten: currently a key may change color 3 times!! First with kbd, then with cat and eventually with key...
So it may be better to keep track of all changes before apply them.

(sorry for bad typing... I'm on my phone)

**Comment by Zer0xFF** [comment]
ya i agree, I was thinking about that for key_set, but it makes sense to have it for all functions...
aka do_work(),do_work(),do_work(),do_work(), apply()

**Comment by cobacdavid** [comment]
Change `dtv2change` and `dtv2reader` codes for a **key by key** change instead of multiple assignments (with `kbd` and then with `cat` and then with `key`). This makes changes of complex configurations much faster.
So I close this issue.
