### ISSUE TITLE
drevo tryfing 2 italian 105 key - some keys are not changing color

### ISSUE THREAD

**Issue by onekk** [cobacdavid/dtv2#7]
Hello. I own a drevo tryfing 2 but the 105 keys italian version,

I have note d that some keys are no modified, so I have copied the fr configuration, and modified to make an italian version:
This is working 

```
# it locale
if 'it' in locale.setlocale(locale.LC_ALL, ''):
    itkeys = {'ù': 0x32,
              '<': 0x64}
    keys.update(itkeys)

```

Same problem with all the keypad keys

```
        #
        'kpnlk': 0x53, 'kpdiv': 0x54, 'kpmul': 0x55, 'kpsub': 0x56,
        'kpadd': 0x57, 'kpent': 0x58, 'kpdot': 0x63,
        #
        'kp1': 0x59, 'kp2': 0x5A,'kp3': 0x5B,'kp4': 0x5C,'kp5': 0x5D,
        'kp6': 0x5E, 'kp7': 0x5F, 'kp8': 0x60, 'kp9': 0x61,
        'kp0': 0x62
```

and in the "key groups", i've added some definition:

```
                             'del', 'end', 'p-down']
                 'kp_digits': ['kp1', 'kp2','kp3','kp4','kp5',
                    'kp6','kp7', 'kp8', 'kp9', 'kp0' ],
                 'kp_oper': ['kpnlk', 'kpdiv','kpmul', 'kpsub',
                      'kpadd', 'kpent','kpdot']

```

I have this setting in .dtv2change file

```
{"kbd": "cyan"}
```
and everything now works

Regards

carlo D.

**Comment by cobacdavid** [comment]
Hi Carlo,
thanks for your feedback. May be you can open a PR? 
Or perhaps I should separate key assigns according to language in some other files, using your config. as "it" default...

Edit: I just realize it's the 104 key version, not mine, the TKL version...

**Comment by onekk** [comment]
Open a PR is possible, I have not done it recently, but maybe it is possible to achieve something.

I knew that is a "different "version, but it has same chip, and same identifier, so i think it has the same configuration, only much  keys connected.

For the code, I have used same way for the "french" localization, or maybe one can put a command line flag or a json "variable" to set keyboard variant maybe 104 keys and language to permit to use it in a more flexible way (in other word with a different language OS, as many programmers, use the OS in English but use localized keyboards).

Let me know what do you think.

Regards

Carlo D.

**Comment by cobacdavid** [comment]
Hi,
I created `en.json` and `fr.json`.
I suggest you open a PR, modify these files and add the specific keys of 105 keys layout, and add a `it.json`.
I tested with those new keys on my TKL keyboard and this has no effect, so it seems useless to test keyboard type.

**Comment by onekk** [comment]
PR done, hope it is correct, let me know if anything is wrong.

I'm not used to do PR so maybe I 've done something wrong.
